[project]
name = "rag-project-project2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "gradio>=6.20.0",
    "llama-index>=0.14.23",
    "llama-index-embeddings-cohere>=0.8.0",
    "llama-index-llms-cohere>=0.8.0",
    "llama-index-llms-google-genai>=0.9.6",
    "llama-index-utils-workflow>=0.11.0",
    "llama-index-vector-stores-pinecone>=0.8.0",
    "pydantic>=2.13.4",
]
